// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("Emp_Vacations_Transactions")]
    public partial class EmpVacationsTransaction
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("empId")]
        public int? EmpId { get; set; }
        [Column("vacationTypeId")]
        public int? VacationTypeId { get; set; }
        [Column("startDate", TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column("finishDate", TypeName = "datetime")]
        public DateTime? FinishDate { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        public bool? HrApprovalStatus { get; set; }

        [ForeignKey("EmpId")]
        [InverseProperty("EmpVacationsTransactions")]
        public virtual User Emp { get; set; }
        [ForeignKey("VacationTypeId")]
        [InverseProperty("EmpVacationsTransactions")]
        public virtual VacationType VacationType { get; set; }
    }
}