// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    public partial class User
    {
        public User()
        {
            EmpVacationCredits = new HashSet<EmpVacationCredit>();
            EmpVacationsTransactions = new HashSet<EmpVacationsTransaction>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("firstName")]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Column("lastName")]
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        [Column("phone")]
        [StringLength(50)]
        public string Phone { get; set; }
        [Column("isHrAdmin")]
        public bool? IsHrAdmin { get; set; }
        [Column("password")]
        [StringLength(100)]
        public string Password { get; set; }
        [Column("departmentId")]
        public int? DepartmentId { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("createdBy")]
        public int? CreatedBy { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("Users")]
        public virtual Department Department { get; set; }
        [InverseProperty("Emp")]
        public virtual ICollection<EmpVacationCredit> EmpVacationCredits { get; set; }
        [InverseProperty("Emp")]
        public virtual ICollection<EmpVacationsTransaction> EmpVacationsTransactions { get; set; }
    }
}