// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("Vacation_Type")]
    public partial class VacationType
    {
        public VacationType()
        {
            EmpVacationCredits = new HashSet<EmpVacationCredit>();
            EmpVacationsTransactions = new HashSet<EmpVacationsTransaction>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("vacationTypeName")]
        [StringLength(50)]
        public string VacationTypeName { get; set; }

        [InverseProperty("VacationType")]
        public virtual ICollection<EmpVacationCredit> EmpVacationCredits { get; set; }
        [InverseProperty("VacationType")]
        public virtual ICollection<EmpVacationsTransaction> EmpVacationsTransactions { get; set; }
    }
}